version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont 
    restart: always
    environment:
    - POSTGRES_DB=postgres_db
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=@dmin2024
    ports:
    - '5432:5432'
    volumes:
    - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local